apiVersion: v1
kind: Service
metadata:
  name: usersservice
spec:
  selector:
    app: userspods
  ports:
    - port: 3000 # Port exposed inside the cluster
      targetPort: 3000 # Port your container listens on
  type: LoadBalancer # Minikube will map this to a NodePort/LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userspods
  template:
    metadata:
      labels:
        app: userspods
    spec:
      containers:
        - name: usercontainer
          image: sebastianmedina25/server20250913:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MONGO_URI # key name, no accidental merge with value
              value: "mongodb+srv://jtatan2014:Bask20177*@cluster0.haka7.mongodb.net/back72855"
            - name: DB_NAME
              value: "comisPruebas"
